server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://clinics-do-user-17950168-0.l.db.ondigitalocean.com:25060/defaultdb?sslmode=require
    username: ${DB_USERNAME}  # Use environment variable for sensitive info
    password: ${DB_PASSWORD}  # Use environment variable for sensitive info
    hikari:
      maximum-pool-size: 10
  web:
    resources:
      static-locations: file:./uploads/
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    generate-ddl: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: false
    drop-first: true
    default-schema: public

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  image: images/
  file.upload-dir: /var/www/uploads

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}  # Use environment variable for sensitive info
  api-key: ${CLOUDINARY_API_KEY}  # Use environment variable for sensitive info
  api-secret: ${CLOUDINARY_API_SECRET}  # Use environment variable for sensitive info
